# Generated by Django 3.0.3 on 2022-01-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('decs', models.TextField(default='')),
                ('img', models.FileField(blank=True, null=True, upload_to='db.File/bytes/filename/mimetype')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=500)),
                ('original_object_uri', models.CharField(default='', max_length=1000)),
                ('resource_type', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('decs', models.TextField(default='')),
                ('price', models.TextField(default='')),
                ('img', models.FileField(blank=True, null=True, upload_to='db.File/bytes/filename/mimetype')),
            ],
        ),
    ]
